---
spring:
  datasource:
    password: jrq.l.iggy09
    url: jdbc:mysql://localhost:3306/ctool?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
  session:
    store-type: redis
  thymeleaf:
    mode: HTML
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
  redis:
    database: 0
    port: 6379
    host: localhost
    timeout: 5000
server:
  port: 8002
mybatis:
  configuration:
    cache-enabled: true
    default-statement-timeout: 3000
    map-underscore-to-camel-case: true
    use-generated-keys: true
dubbo:
  registry:
    address: zookeeper://127.0.0.1:2181
    client: zkclient
  protocol:
    port: 20880
    name: dubbo
  application:
    name: pservice
  consumer:
    check: false
